insert into clients (name) values ('Quamba');
insert into clients (name) values ('Innotype');
insert into clients (name) values ('Pixope');
insert into clients (name) values ('Christopher Rogers');
insert into clients (name) values ('Gerald Green');
insert into clients (name) values ('Carl Ward');
insert into contacts (name, address, phone, email, client_id) values ('Carolyn Ferguson', 'Ilha de Moçambique, 418 Shoshone Avenue', '258-(777)701-9591', 'cferguson0@xinhuanet.com', 1);
insert into contacts (name, address, phone, email, client_id) values ('Ryan Ferguson', 'Arras, 63137 Swallow Point', '33-(367)941-6128', 'rferguson1@phoca.cz', 1);
insert into contacts (name, address, phone, email, client_id) values ('Roger Fuller', 'Lâm Thao, 63904 Transport Circle', '84-(559)333-4603', 'rfuller2@qq.com', 2);
insert into contacts (name, address, phone, email, client_id) values ('Earl Martin', 'Kaliro, 21 Russell Pass', '256-(492)915-2419', 'emartin3@google.co.uk', 2);
insert into contacts (name, address, phone, email, client_id) values ('Shirley Howard', 'Buritis, 39 Shopko Alley', '55-(103)210-0409', 'showard4@hud.gov', 2);
insert into contacts (name, address, phone, email, client_id) values ('Sarah Elliott', 'Muff, 311 Fordem Place', '353-(996)395-9441', 'selliott5@cpanel.net', 3);
insert into contacts (name, address, phone, email, client_id) values ('Paul Jenkins', 'Qaxbas, 401 Buhler Street', '994-(858)587-6308', 'pjenkins6@youtu.be', 3);
insert into contacts (name, address, phone, email, client_id) values ('Robin Nelson', 'Nowshahr, 888 Londonderry Trail', '98-(144)150-8912', 'rnelson7@prnewswire.com', 2);
insert into contacts (name, address, phone, email, client_id) values ('George Ford', 'Fontana, 5 Springs Point', '54-(314)241-5944', 'gford8@ihg.com', 3);
insert into contacts (name, address, phone, email, client_id) values ('Christopher Rogers', 'El Refugio, 95174 Sommers Terrace', '52-(841)350-3963', 'hrobinson0@clickbank.net', 4);
insert into contacts (name, address, phone, email, client_id) values ('Gerald Green', 'Yunxi, 693 Mayfield Alley', '86-(494)399-1459', 'blopez1@uiuc.edu', 5);
insert into contacts (name, address, phone, email, client_id) values ('Carl Ward', 'Moncada, 060 Bultman Circle', '63-(484)530-4182', 'kjordan2@ucoz.com', 6);
insert into contacts (name, address, phone, email, client_id) values ('Helena Ward', 'Moncada, 060 Bultman Circle', '63-(484)531-2386', 'hward@ucoz.com', 6);
insert into services (name, price) values ('Land issues', 1000);
insert into services (name, price) values ('Collection of debts', 500);
insert into services (name, price) values ('Representation in court', 1000);
insert into services (name, price) values ('Inheritance issues', 500);
insert into servants (name, address, phone, email, education_level, position) values ('Gregory Nichols', 'Guanghai, 3682 Arapahoe Court', '86-(263)882-3753', 'gnichols0@symantec.com', 'Bachelor of Laws', 'Administrative Assistant');
insert into servants (name, address, phone, email, education_level, position) values ('Christopher Gordon', 'Sagud-Bahley, 918 Gerald Terrace', '63-(741)398-6820', 'cgordon1@sakura.ne.jp', 'Master of Laws', 'Lawyer');
insert into servants (name, address, phone, email, education_level, position) values ('Katherine Rose', 'Socorro, 1 Blaine Lane', '57-(285)693-1746', 'krose2@noaa.gov', 'Doctor of Juridical Science', 'Clerk');
insert into servants (name, address, phone, email, education_level, position) values ('Charles Parker', 'Montenegro, 6063 Bunting Terrace', '55-(837)390-9914', 'cparker3@gravatar.com', 'Specialist in law', 'Lawyer');
insert into servants (name, address, phone, email, education_level, position) values ('Jane Jones', 'Malambo, 222 Burning Wood Avenue', '57-(848)871-4330', 'jjones4@nyu.edu', 'Bachelor of Laws', 'Lawyer');
insert into contracts (service, client, time_start, time_end) values (1, 1, '2016-10-07 17:05:44', '2016-10-14 10:07:36');
insert into contracts (service, client, time_start, time_end) values (4, 3, '2016-06-06 08:05:46', '2016-09-20 06:09:49');
insert into contracts (service, client, time_start, time_end) values (2, 3, '2016-05-15 13:05:39', '2016-05-25 11:24:27');
insert into contracts (service, client, time_start, time_end) values (4, 5, '2016-09-03 13:42:10', '2017-02-02 20:52:20');
insert into contracts (service, client, time_start, time_end) values (3, 6, '2016-05-21 16:54:58', '2016-06-14 03:15:31');
insert into contract_servant (servant, contract) values (1, 3);
insert into contract_servant (servant, contract) values (2, 4);
insert into contract_servant (servant, contract) values (2, 2);
insert into contract_servant (servant, contract) values (5, 5);
insert into contract_servant (servant, contract) values (4, 1);
insert into contract_servant (servant, contract) values (4, 2);
insert into contract_servant (servant, contract) values (3, 4);
